// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqA8ihKfflr7bzAFjBY0fsbHEAvmv7yLQ',
    appId: '1:267614500563:web:08dac09cc37d60290bc626',
    messagingSenderId: '267614500563',
    projectId: 'legalai-bbecd',
    authDomain: 'legalai-bbecd.firebaseapp.com',
    storageBucket: 'legalai-bbecd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxm3Uued1_MJ51TGhT1401vRweM-h62SA',
    appId: '1:267614500563:android:0aec2118b8ed372b0bc626',
    messagingSenderId: '267614500563',
    projectId: 'legalai-bbecd',
    storageBucket: 'legalai-bbecd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf1_erJGFUyUUsZ2NTlw2OEjoFa5Vu0tQ',
    appId: '1:267614500563:ios:8be52cd3894cbadf0bc626',
    messagingSenderId: '267614500563',
    projectId: 'legalai-bbecd',
    storageBucket: 'legalai-bbecd.appspot.com',
    iosBundleId: 'com.example.legalai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf1_erJGFUyUUsZ2NTlw2OEjoFa5Vu0tQ',
    appId: '1:267614500563:ios:8be52cd3894cbadf0bc626',
    messagingSenderId: '267614500563',
    projectId: 'legalai-bbecd',
    storageBucket: 'legalai-bbecd.appspot.com',
    iosBundleId: 'com.example.legalai',
  );
}
